// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyutrzccjmcrwnxwupuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dXRyemNjam1jcndueHd1cHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTc5ODAsImV4cCI6MjA3MzY3Mzk4MH0.uDYwCTybDB22g9eIvhoJB3iRDuhw_mcSeG56q6f9CPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});